### ISSUE TITLE
ImportError: cannot import name 'resolve_se_args' from 'timm.models.efficientnet_blocks'

### ISSUE THREAD

**Issue by sekhaish** [changlin31/BossNAS#13]
Hi there, I am trying to search on NATS-Bench using CIFAR 10 dataset and encountered this error. Could you kindly help me with this?

**Comment by sekhaish** [comment]
Pasting the entire thing here!

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    import bossnas  # register hooks
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/__init__.py", line 3, in <module>
    import bossnas.models
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/__init__.py", line 5, in <module>
    from bossnas.models.supernets.hytra_supernet import SupernetHyTra
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/supernets/hytra_supernet.py", line 7, in <module>
    from bossnas.models.operations.operation_dict import OPS
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/operations/operation_dict.py", line 3, in <module>
    from .mbconv_ops import InvertedResidual
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/operations/mbconv_ops.py", line 2, in <module>
    from timm.models.efficientnet_blocks import make_divisible, SqueezeExcite, resolve_se_args
ImportError: cannot import name 'resolve_se_args' from 'timm.models.efficientnet_blocks' (/anaconda/lib/python3.8/site-packages/timm/models/efficientnet_blocks.py)
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    import bossnas  # register hooks
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/__init__.py", line 3, in <module>
    import bossnas.models
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/__init__.py", line 5, in <module>
    from bossnas.models.supernets.hytra_supernet import SupernetHyTra
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/supernets/hytra_supernet.py", line 7, in <module>
    from bossnas.models.operations.operation_dict import OPS
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/operations/operation_dict.py", line 3, in <module>
    from .mbconv_ops import InvertedResidual
  File "/home/vishwam/aishu/BossNAS/BossNAS/searching/bossnas/models/operations/mbconv_ops.py", line 2, in <module>
    from timm.models.efficientnet_blocks import make_divisible, SqueezeExcite, resolve_se_args
ImportError: cannot import name 'resolve_se_args' from 'timm.models.efficientnet_blocks' (/anaconda/lib/python3.8/site-packages/timm/models/efficientnet_blocks.py)
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28409 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 28408) of binary: /anaconda/bin/python
Traceback (most recent call last):
  File "/anaconda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/anaconda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/anaconda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/anaconda/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/anaconda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-10_19:38:27
  host      : vv-gpu2002-nc12s-v3.internal.cloudapp.net
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 28408)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by changlin31** [comment]
Hi @sekhaish 

It seems an import error. What is your `timm` version? We use 0.3.2.
`pip install timm==0.3.2`

**Comment by sekhaish** [comment]
Hi @changlin31 , thank you for your response. 
Yes, I made sure the version is 0.3.2 and it did not work. I got the error as above. I tried playing around with a few versions and the error did not change.

**Comment by changlin31** [comment]
It's weird. Could you try start a python console in your environment and run:

```
import timm
timm.__version__
from timm.models.efficientnet_blocks import make_divisible, SqueezeExcite, resolve_se_args
```

For my environment, it outputs this and yields no error:
`'0.3.2'`

**Comment by sekhaish** [comment]
![Screenshot from 2022-03-11 11-31-22](https://user-images.githubusercontent.com/81991428/157811423-2b95f80e-86e5-40dd-bef9-be8f7d3c2e9a.png)
Hi @changlin31 
upon downgrading the torch version to 1.7.0 with Ttimm 0.3.2, I was able to run it without any errors. Thanks for your time. much appreciated.
